"""empty message

Revision ID: 88d88f09094e
Revises: 866d89ea99fb
Create Date: 2024-06-20 15:29:55.961496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d88f09094e'
down_revision = '866d89ea99fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprunt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_debut', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprunt', schema=None) as batch_op:
        batch_op.drop_column('date_debut')

    # ### end Alembic commands ###
