"""empty message

Revision ID: dbe170a83f2b
Revises: bd25b7c47234
Create Date: 2024-06-19 11:49:48.130703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe170a83f2b'
down_revision = 'bd25b7c47234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('auteur', sa.String(length=200), nullable=True),
    sa.Column('genre', sa.String(length=200), nullable=True),
    sa.Column('datepub', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livre')
    # ### end Alembic commands ###
