"""empty message

Revision ID: f7d1ea5e7816
Revises: dbe170a83f2b
Create Date: 2024-06-19 12:15:16.607171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d1ea5e7816'
down_revision = 'dbe170a83f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livre', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
